apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: apac-bc-squad-1-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: quay.io/poornimata/squad1-app
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-cohort/squad1-app-repo.git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: install-dependencies
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: ARGS
          value:
            - clean-install
        - name: PATH_CONTEXT
          value: nodejs-app/entity-view-app/ 
      runAfter:
        - clone-repository
    - name: build-image
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
        - name: CONTEXT
          value: nodejs-app/entity-view-app
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data 
    - name: kustomize-build
      runAfter:
        - build-image
      params:
         - name: image-with-tag
           value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: kustomize-build
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: gitops
      runAfter:
        - kustomize-build
      taskRef:
        kind: Task
        name: gitops
      params:
        - name: app-name
          value: squad1-app
        - name: sha
          value: "$(tasks.clone-repository.results.commit)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data


        
